repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format staged files
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: true
      - id: ruff-check
        name: ruff check staged files
        entry: ruff check
        language: system
        types: [python]
        pass_filenames: true
